name: uuid7
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/qcrg/dart_uuid7

environment:
  sdk: >=2.12.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
